# Generated by Django 6.1.1 on 2026-10-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_image_course_is_published_course_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
