from django.urls import path

from .assessment_views import (
    AssignmentDetailV1,
    AssignmentListCreateV1,
    AssignmentSubmissionDetailV1,
    AssignmentSubmissionListCreateV1,
    ChoiceDetailV1,
    QuizAttemptDetailV1,
    QuizAttemptsV1,
    QuizDetailV1,
    QuizListCreateV1,
    QuizQuestionListCreateV1,
    QuestionChoiceListCreateV1,
    QuestionDetailV1,
)
from .api_views import (
    AdminEnrollmentListV1,
    CategoryDetailV1,
    CategoryListCreateV1,
    CourseCatalogV1,
    CourseDetailV1,
    CourseReviewDetailV1,
    CourseReviewListCreateV1,
    CourseSectionsV1,
    EnrollmentProgressV1,
    EnrollmentReportV1,
    LessonDetailV1,
    LessonResourcesV1,
    ManualEnrollmentCreateV1,
    ResourceDetailV1,
    ResourceDownloadV1,
    SectionDetailV1,
    SectionLessonsV1,
    StudentDashboardV1,
)

urlpatterns = [
    path('<slug:course_slug>/quizzes/', QuizListCreateV1.as_view(), name='api-v1-course-quizzes'),
    path('quizzes/<int:pk>/', QuizDetailV1.as_view(), name='api-v1-quiz-detail'),
    path('quizzes/<int:quiz_pk>/questions/', QuizQuestionListCreateV1.as_view(), name='api-v1-quiz-questions'),
    path('questions/<int:pk>/', QuestionDetailV1.as_view(), name='api-v1-question-detail'),
    path('questions/<int:question_pk>/choices/', QuestionChoiceListCreateV1.as_view(), name='api-v1-question-choices'),
    path('choices/<int:pk>/', ChoiceDetailV1.as_view(), name='api-v1-choice-detail'),
    path('quizzes/<int:quiz_pk>/attempts/', QuizAttemptsV1.as_view(), name='api-v1-quiz-attempts'),
    path('quiz-attempts/<int:pk>/', QuizAttemptDetailV1.as_view(), name='api-v1-quiz-attempt-detail'),
    path('<slug:course_slug>/assignments/', AssignmentListCreateV1.as_view(), name='api-v1-course-assignments'),
    path('assignments/<int:pk>/', AssignmentDetailV1.as_view(), name='api-v1-assignment-detail'),
    path('assignments/<int:assignment_pk>/submissions/', AssignmentSubmissionListCreateV1.as_view(), name='api-v1-assignment-submissions'),
    path('submissions/<int:pk>/', AssignmentSubmissionDetailV1.as_view(), name='api-v1-assignment-submission-detail'),
    path('dashboard/', StudentDashboardV1.as_view(), name='api-v1-student-dashboard'),
    path('enrollments/<int:enrollment_pk>/progress/', EnrollmentProgressV1.as_view(), name='api-v1-enrollment-progress'),
    path('admin/manual-enrol/', ManualEnrollmentCreateV1.as_view(), name='api-v1-admin-manual-enrollment'),
    path('admin/enrollments/', AdminEnrollmentListV1.as_view(), name='api-v1-admin-enrollments'),
    path('admin/reports/enrollments/', EnrollmentReportV1.as_view(), name='api-v1-admin-enrollment-report'),
    path('categories/', CategoryListCreateV1.as_view(), name='api-v1-category-list'),
    path('categories/<slug:slug>/', CategoryDetailV1.as_view(), name='api-v1-category-detail'),
    path('sections/<int:pk>/', SectionDetailV1.as_view(), name='api-v1-section-detail'),
    path('sections/<int:section_pk>/lessons/', SectionLessonsV1.as_view(), name='api-v1-section-lessons'),
    path('lessons/<int:pk>/', LessonDetailV1.as_view(), name='api-v1-lesson-detail'),
    path('lessons/<int:lesson_pk>/resources/', LessonResourcesV1.as_view(), name='api-v1-lesson-resources'),
    path('resources/<int:pk>/download/', ResourceDownloadV1.as_view(), name='api-v1-resource-download'),
    path('resources/<int:pk>/', ResourceDetailV1.as_view(), name='api-v1-resource-detail'),
    path('<slug:course_slug>/sections/', CourseSectionsV1.as_view(), name='api-v1-course-sections'),
    path('<slug:course_slug>/reviews/', CourseReviewListCreateV1.as_view(), name='api-v1-course-reviews'),
    path('reviews/<int:pk>/', CourseReviewDetailV1.as_view(), name='api-v1-review-detail'),
    path('<slug:slug>/', CourseDetailV1.as_view(), name='api-v1-course-detail'),
    path('', CourseCatalogV1.as_view(), name='api-v1-course-list'),
]