# Generated by Django 6.1.1 on 2026-10-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPathResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.TextField(max_length=2000)),
                ('current_skill_level', models.CharField(max_length=40)),
                ('interests', models.TextField(max_length=2000)),
                ('hours_per_week', models.PositiveSmallIntegerField()),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('recommendation_summary', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
