# Generated by Django 6.1.1 on 2026-10-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_question_assignment_assignmentsubmission_choice_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('certificate', 'Certificate'), ('short_course', 'Short course')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='delivery_modes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='intake_status',
            field=models.CharField(blank=True, choices=[('ongoing', 'Ongoing'), ('upcoming', 'Upcoming'), ('closed', 'Closed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='whatsapp_inquiry_url',
            field=models.URLField(blank=True),
        ),
    ]
