# Generated by Django 6.1.1 on 2026-09-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_instructor',
            field=models.BooleanField(default=False, help_text='True only once an admin approves this account as a real instructor.'),
        ),
    ]
