# Generated by Django 6.1.1 on 2026-10-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_cart_cartitem_order_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_email_last_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
